### ISSUE TITLE
There's no index.js

### ISSUE THREAD

**Issue by new-hue** [oHeckGage/Anonymous-Static#2]
To run this it requires a index.js however there is none. I'd like to run my own instance of this.

**Comment by oHeckGage** [comment]
If you're using a repl, make sure its an HTML, CSS, JS repl, not Node.js. This is STATIC meaning there's no core server or javascript files to run it.

**Comment by new-hue** [comment]
thank you

**Comment by new-hue** [comment]
I got it working but now whenever i use it it says this:
![image](https://user-images.githubusercontent.com/89873236/188022905-d2e85cc6-fc0a-45cb-aa5b-b43c4a983c8b.png)

**Comment by new-hue** [comment]
But it then loads after I reload the page.

**Comment by new-hue** [comment]
Nvm
